// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/interfluid/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSendInterfluidDelegatePacketData struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Port             string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	ChannelID        string `protobuf:"bytes,3,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TimeoutTimestamp uint64 `protobuf:"varint,4,opt,name=timeoutTimestamp,proto3" json:"timeoutTimestamp,omitempty"`
	DelAddr          string `protobuf:"bytes,5,opt,name=delAddr,proto3" json:"delAddr,omitempty"`
	ValAddr          string `protobuf:"bytes,6,opt,name=valAddr,proto3" json:"valAddr,omitempty"`
	Coin             string `protobuf:"bytes,7,opt,name=coin,proto3" json:"coin,omitempty"`
}

func (m *MsgSendInterfluidDelegatePacketData) Reset()         { *m = MsgSendInterfluidDelegatePacketData{} }
func (m *MsgSendInterfluidDelegatePacketData) String() string { return proto.CompactTextString(m) }
func (*MsgSendInterfluidDelegatePacketData) ProtoMessage()    {}
func (*MsgSendInterfluidDelegatePacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf2ec86ec612e19, []int{0}
}
func (m *MsgSendInterfluidDelegatePacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendInterfluidDelegatePacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendInterfluidDelegatePacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendInterfluidDelegatePacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendInterfluidDelegatePacketData.Merge(m, src)
}
func (m *MsgSendInterfluidDelegatePacketData) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendInterfluidDelegatePacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendInterfluidDelegatePacketData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendInterfluidDelegatePacketData proto.InternalMessageInfo

func (m *MsgSendInterfluidDelegatePacketData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendInterfluidDelegatePacketData) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *MsgSendInterfluidDelegatePacketData) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *MsgSendInterfluidDelegatePacketData) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

func (m *MsgSendInterfluidDelegatePacketData) GetDelAddr() string {
	if m != nil {
		return m.DelAddr
	}
	return ""
}

func (m *MsgSendInterfluidDelegatePacketData) GetValAddr() string {
	if m != nil {
		return m.ValAddr
	}
	return ""
}

func (m *MsgSendInterfluidDelegatePacketData) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

type MsgSendInterfluidDelegatePacketDataResponse struct {
}

func (m *MsgSendInterfluidDelegatePacketDataResponse) Reset() {
	*m = MsgSendInterfluidDelegatePacketDataResponse{}
}
func (m *MsgSendInterfluidDelegatePacketDataResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgSendInterfluidDelegatePacketDataResponse) ProtoMessage() {}
func (*MsgSendInterfluidDelegatePacketDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf2ec86ec612e19, []int{1}
}
func (m *MsgSendInterfluidDelegatePacketDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendInterfluidDelegatePacketDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendInterfluidDelegatePacketDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendInterfluidDelegatePacketDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendInterfluidDelegatePacketDataResponse.Merge(m, src)
}
func (m *MsgSendInterfluidDelegatePacketDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendInterfluidDelegatePacketDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendInterfluidDelegatePacketDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendInterfluidDelegatePacketDataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSendInterfluidDelegatePacketData)(nil), "osmosis.v12.interfluid.MsgSendInterfluidDelegatePacketData")
	proto.RegisterType((*MsgSendInterfluidDelegatePacketDataResponse)(nil), "osmosis.v12.interfluid.MsgSendInterfluidDelegatePacketDataResponse")
}

func init() { proto.RegisterFile("osmosis/interfluid/tx.proto", fileDescriptor_ccf2ec86ec612e19) }

var fileDescriptor_ccf2ec86ec612e19 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xbd, 0x4a, 0x03, 0x41,
	0x14, 0x85, 0x33, 0x26, 0x26, 0x64, 0x2a, 0x99, 0x42, 0x06, 0x95, 0x25, 0xc4, 0x26, 0x28, 0xd9,
	0x25, 0x11, 0x6c, 0xac, 0xd4, 0x34, 0x29, 0x02, 0x21, 0x5a, 0xd9, 0x4d, 0x76, 0xaf, 0x9b, 0xc1,
	0xdd, 0x99, 0x65, 0xe6, 0x26, 0xc4, 0xb7, 0xf0, 0x21, 0x2c, 0x7d, 0x10, 0xcb, 0x94, 0x96, 0x92,
	0xe0, 0x7b, 0xc8, 0xfe, 0xc4, 0x20, 0x0a, 0x06, 0xec, 0xee, 0x39, 0xdf, 0x2e, 0xe7, 0xcc, 0xe5,
	0xd2, 0x43, 0x6d, 0x63, 0x6d, 0xa5, 0xf5, 0xa4, 0x42, 0x30, 0xf7, 0xd1, 0x54, 0x06, 0x1e, 0xce,
	0xdd, 0xc4, 0x68, 0xd4, 0x6c, 0xbf, 0x80, 0xee, 0xac, 0xd3, 0x75, 0x37, 0x1f, 0x34, 0x3f, 0x08,
	0x3d, 0x1e, 0xd8, 0xf0, 0x06, 0x54, 0xd0, 0xff, 0x72, 0x7b, 0x10, 0x41, 0x28, 0x10, 0x86, 0xc2,
	0x7f, 0x00, 0xec, 0x09, 0x14, 0x8c, 0xd3, 0x9a, 0x6f, 0x40, 0xa0, 0x36, 0x9c, 0x34, 0x48, 0xab,
	0x3e, 0x5a, 0x4b, 0xc6, 0x68, 0x25, 0xd1, 0x06, 0xf9, 0x4e, 0x66, 0x67, 0x33, 0x3b, 0xa2, 0x75,
	0x7f, 0x22, 0x94, 0x82, 0xa8, 0xdf, 0xe3, 0xe5, 0x0c, 0x6c, 0x0c, 0x76, 0x42, 0xf7, 0x50, 0xc6,
	0xa0, 0xa7, 0x78, 0x2b, 0x63, 0xb0, 0x28, 0xe2, 0x84, 0x57, 0x1a, 0xa4, 0x55, 0x19, 0xfd, 0xf0,
	0xd3, 0xdc, 0x00, 0xa2, 0xcb, 0x20, 0x30, 0x7c, 0x37, 0xcf, 0x2d, 0x64, 0x4a, 0x66, 0x22, 0x27,
	0xd5, 0x9c, 0x14, 0x32, 0x6d, 0xe4, 0x6b, 0xa9, 0x78, 0x2d, 0x6f, 0x94, 0xce, 0xcd, 0x36, 0x3d,
	0xdd, 0xe2, 0x99, 0x23, 0xb0, 0x89, 0x56, 0x16, 0xba, 0x2f, 0x84, 0x96, 0x07, 0x36, 0x64, 0xcf,
	0x84, 0x36, 0xfe, 0xdc, 0xcd, 0x85, 0xfb, 0xfb, 0x72, 0xdd, 0x2d, 0x12, 0x0f, 0xae, 0xff, 0xf1,
	0xf3, 0xba, 0xee, 0xd5, 0xf0, 0x75, 0xe9, 0x90, 0xc5, 0xd2, 0x21, 0xef, 0x4b, 0x87, 0x3c, 0xad,
	0x9c, 0xd2, 0x62, 0xe5, 0x94, 0xde, 0x56, 0x4e, 0xe9, 0xee, 0x3c, 0x94, 0x38, 0x99, 0x8e, 0x5d,
	0x5f, 0xc7, 0x5e, 0x11, 0xd4, 0x8e, 0xc4, 0xd8, 0xae, 0x85, 0x37, 0xeb, 0x74, 0xbd, 0xf9, 0xb7,
	0x93, 0x79, 0x4c, 0xc0, 0x8e, 0xab, 0xd9, 0xd9, 0x9c, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7d,
	0x87, 0xd7, 0xa0, 0x55, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SendInterfluidDelegatePacketData(ctx context.Context, in *MsgSendInterfluidDelegatePacketData, opts ...grpc.CallOption) (*MsgSendInterfluidDelegatePacketDataResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendInterfluidDelegatePacketData(ctx context.Context, in *MsgSendInterfluidDelegatePacketData, opts ...grpc.CallOption) (*MsgSendInterfluidDelegatePacketDataResponse, error) {
	out := new(MsgSendInterfluidDelegatePacketDataResponse)
	err := c.cc.Invoke(ctx, "/osmosis.v12.interfluid.Msg/SendInterfluidDelegatePacketData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SendInterfluidDelegatePacketData(context.Context, *MsgSendInterfluidDelegatePacketData) (*MsgSendInterfluidDelegatePacketDataResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SendInterfluidDelegatePacketData(ctx context.Context, req *MsgSendInterfluidDelegatePacketData) (*MsgSendInterfluidDelegatePacketDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInterfluidDelegatePacketData not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SendInterfluidDelegatePacketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendInterfluidDelegatePacketData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendInterfluidDelegatePacketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.v12.interfluid.Msg/SendInterfluidDelegatePacketData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendInterfluidDelegatePacketData(ctx, req.(*MsgSendInterfluidDelegatePacketData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.v12.interfluid.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInterfluidDelegatePacketData",
			Handler:    _Msg_SendInterfluidDelegatePacketData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/interfluid/tx.proto",
}

func (m *MsgSendInterfluidDelegatePacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendInterfluidDelegatePacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendInterfluidDelegatePacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coin) > 0 {
		i -= len(m.Coin)
		copy(dAtA[i:], m.Coin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Coin)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ValAddr) > 0 {
		i -= len(m.ValAddr)
		copy(dAtA[i:], m.ValAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddr)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DelAddr) > 0 {
		i -= len(m.DelAddr)
		copy(dAtA[i:], m.DelAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DelAddr)))
		i--
		dAtA[i] = 0x2a
	}
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChannelID) > 0 {
		i -= len(m.ChannelID)
		copy(dAtA[i:], m.ChannelID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Port) > 0 {
		i -= len(m.Port)
		copy(dAtA[i:], m.Port)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Port)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendInterfluidDelegatePacketDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendInterfluidDelegatePacketDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendInterfluidDelegatePacketDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSendInterfluidDelegatePacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Port)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.TimeoutTimestamp))
	}
	l = len(m.DelAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ValAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Coin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendInterfluidDelegatePacketDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSendInterfluidDelegatePacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendInterfluidDelegatePacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendInterfluidDelegatePacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Port = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendInterfluidDelegatePacketDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendInterfluidDelegatePacketDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendInterfluidDelegatePacketDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
