// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/interfluidsender/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgInterfluidDelegate struct {
	Sender  string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty" yaml:"sender"`
	LockId  uint64 `protobuf:"varint,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	ValAddr string `protobuf:"bytes,3,opt,name=val_addr,json=valAddr,proto3" json:"val_addr,omitempty"`
}

func (m *MsgInterfluidDelegate) Reset()         { *m = MsgInterfluidDelegate{} }
func (m *MsgInterfluidDelegate) String() string { return proto.CompactTextString(m) }
func (*MsgInterfluidDelegate) ProtoMessage()    {}
func (*MsgInterfluidDelegate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8d6c71ce3aa2066, []int{0}
}
func (m *MsgInterfluidDelegate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInterfluidDelegate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInterfluidDelegate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInterfluidDelegate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInterfluidDelegate.Merge(m, src)
}
func (m *MsgInterfluidDelegate) XXX_Size() int {
	return m.Size()
}
func (m *MsgInterfluidDelegate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInterfluidDelegate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInterfluidDelegate proto.InternalMessageInfo

func (m *MsgInterfluidDelegate) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgInterfluidDelegate) GetLockId() uint64 {
	if m != nil {
		return m.LockId
	}
	return 0
}

func (m *MsgInterfluidDelegate) GetValAddr() string {
	if m != nil {
		return m.ValAddr
	}
	return ""
}

type MsgInterfluidDelegateResponse struct {
}

func (m *MsgInterfluidDelegateResponse) Reset()         { *m = MsgInterfluidDelegateResponse{} }
func (m *MsgInterfluidDelegateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInterfluidDelegateResponse) ProtoMessage()    {}
func (*MsgInterfluidDelegateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8d6c71ce3aa2066, []int{1}
}
func (m *MsgInterfluidDelegateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInterfluidDelegateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInterfluidDelegateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInterfluidDelegateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInterfluidDelegateResponse.Merge(m, src)
}
func (m *MsgInterfluidDelegateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInterfluidDelegateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInterfluidDelegateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInterfluidDelegateResponse proto.InternalMessageInfo

type MsgInterfluidUndelegate struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty" yaml:"sender"`
	LockId uint64 `protobuf:"varint,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
}

func (m *MsgInterfluidUndelegate) Reset()         { *m = MsgInterfluidUndelegate{} }
func (m *MsgInterfluidUndelegate) String() string { return proto.CompactTextString(m) }
func (*MsgInterfluidUndelegate) ProtoMessage()    {}
func (*MsgInterfluidUndelegate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8d6c71ce3aa2066, []int{2}
}
func (m *MsgInterfluidUndelegate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInterfluidUndelegate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInterfluidUndelegate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInterfluidUndelegate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInterfluidUndelegate.Merge(m, src)
}
func (m *MsgInterfluidUndelegate) XXX_Size() int {
	return m.Size()
}
func (m *MsgInterfluidUndelegate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInterfluidUndelegate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInterfluidUndelegate proto.InternalMessageInfo

func (m *MsgInterfluidUndelegate) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgInterfluidUndelegate) GetLockId() uint64 {
	if m != nil {
		return m.LockId
	}
	return 0
}

type MsgInterfluidUndelegateResponse struct {
}

func (m *MsgInterfluidUndelegateResponse) Reset()         { *m = MsgInterfluidUndelegateResponse{} }
func (m *MsgInterfluidUndelegateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInterfluidUndelegateResponse) ProtoMessage()    {}
func (*MsgInterfluidUndelegateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8d6c71ce3aa2066, []int{3}
}
func (m *MsgInterfluidUndelegateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInterfluidUndelegateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInterfluidUndelegateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInterfluidUndelegateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInterfluidUndelegateResponse.Merge(m, src)
}
func (m *MsgInterfluidUndelegateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInterfluidUndelegateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInterfluidUndelegateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInterfluidUndelegateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgInterfluidDelegate)(nil), "osmosis.v12.interfluidsender.MsgInterfluidDelegate")
	proto.RegisterType((*MsgInterfluidDelegateResponse)(nil), "osmosis.v12.interfluidsender.MsgInterfluidDelegateResponse")
	proto.RegisterType((*MsgInterfluidUndelegate)(nil), "osmosis.v12.interfluidsender.MsgInterfluidUndelegate")
	proto.RegisterType((*MsgInterfluidUndelegateResponse)(nil), "osmosis.v12.interfluidsender.MsgInterfluidUndelegateResponse")
}

func init() { proto.RegisterFile("osmosis/interfluidsender/tx.proto", fileDescriptor_b8d6c71ce3aa2066) }

var fileDescriptor_b8d6c71ce3aa2066 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcc, 0x2f, 0xce, 0xcd,
	0x2f, 0xce, 0x2c, 0xd6, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0xcb, 0x29, 0xcd, 0x4c, 0x29, 0x4e,
	0xcd, 0x4b, 0x49, 0x2d, 0xd2, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x81,
	0x2a, 0xd1, 0x2b, 0x33, 0x34, 0xd2, 0x43, 0x57, 0x26, 0x25, 0x92, 0x9e, 0x9f, 0x9e, 0x0f, 0x56,
	0xa8, 0x0f, 0x62, 0x41, 0xf4, 0x28, 0x95, 0x71, 0x89, 0xfa, 0x16, 0xa7, 0x7b, 0xc2, 0x15, 0xbb,
	0xa4, 0xe6, 0xa4, 0xa6, 0x27, 0x96, 0xa4, 0x0a, 0x69, 0x72, 0xb1, 0x41, 0x34, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x3a, 0x09, 0x7e, 0xba, 0x27, 0xcf, 0x5b, 0x99, 0x98, 0x9b, 0x63, 0xa5, 0x04,
	0x11, 0x57, 0x0a, 0x82, 0x2a, 0x10, 0x12, 0xe7, 0x62, 0xcf, 0xc9, 0x4f, 0xce, 0x8e, 0xcf, 0x4c,
	0x91, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x09, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0x24, 0xb9, 0x38,
	0xca, 0x12, 0x73, 0xe2, 0x13, 0x53, 0x52, 0x8a, 0x24, 0x98, 0x41, 0xa6, 0x04, 0xb1, 0x97, 0x25,
	0xe6, 0x38, 0xa6, 0xa4, 0x14, 0x29, 0xc9, 0x73, 0xc9, 0x62, 0xb5, 0x37, 0x28, 0xb5, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0x55, 0x29, 0x96, 0x4b, 0x1c, 0x45, 0x41, 0x68, 0x5e, 0x0a, 0x15, 0x9d, 0xa6,
	0xa4, 0xc8, 0x25, 0x8f, 0xc3, 0x78, 0x98, 0x0b, 0x8c, 0xe6, 0x32, 0x71, 0x31, 0xfb, 0x16, 0xa7,
	0x0b, 0xb5, 0x31, 0x72, 0x09, 0x61, 0x09, 0x20, 0x63, 0x3d, 0x7c, 0xc1, 0xad, 0x87, 0xd5, 0x77,
	0x52, 0xd6, 0x64, 0x68, 0x82, 0x39, 0x48, 0xa8, 0x87, 0x91, 0x4b, 0x04, 0x6b, 0x80, 0x98, 0x92,
	0x60, 0x2a, 0x42, 0x9b, 0x94, 0x2d, 0x59, 0xda, 0x60, 0xce, 0x71, 0x0a, 0x3b, 0xf1, 0x48, 0x8e,
	0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58,
	0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x9b, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4,
	0xfc, 0x5c, 0x7d, 0xa8, 0x15, 0xba, 0x39, 0x89, 0x49, 0xc5, 0x30, 0x8e, 0x7e, 0x99, 0xa1, 0x91,
	0x7e, 0x05, 0x96, 0x94, 0x5c, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x4e, 0x99, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb4, 0x9f, 0x9d, 0x4c, 0xf2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Execute superfluid delegation for a lockup
	InterfluidDelegate(ctx context.Context, in *MsgInterfluidDelegate, opts ...grpc.CallOption) (*MsgInterfluidDelegateResponse, error)
	// Execute superfluid undelegation for a lockup
	InterfluidUndelegate(ctx context.Context, in *MsgInterfluidUndelegate, opts ...grpc.CallOption) (*MsgInterfluidUndelegateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) InterfluidDelegate(ctx context.Context, in *MsgInterfluidDelegate, opts ...grpc.CallOption) (*MsgInterfluidDelegateResponse, error) {
	out := new(MsgInterfluidDelegateResponse)
	err := c.cc.Invoke(ctx, "/osmosis.v12.interfluidsender.Msg/InterfluidDelegate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InterfluidUndelegate(ctx context.Context, in *MsgInterfluidUndelegate, opts ...grpc.CallOption) (*MsgInterfluidUndelegateResponse, error) {
	out := new(MsgInterfluidUndelegateResponse)
	err := c.cc.Invoke(ctx, "/osmosis.v12.interfluidsender.Msg/InterfluidUndelegate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Execute superfluid delegation for a lockup
	InterfluidDelegate(context.Context, *MsgInterfluidDelegate) (*MsgInterfluidDelegateResponse, error)
	// Execute superfluid undelegation for a lockup
	InterfluidUndelegate(context.Context, *MsgInterfluidUndelegate) (*MsgInterfluidUndelegateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) InterfluidDelegate(ctx context.Context, req *MsgInterfluidDelegate) (*MsgInterfluidDelegateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterfluidDelegate not implemented")
}
func (*UnimplementedMsgServer) InterfluidUndelegate(ctx context.Context, req *MsgInterfluidUndelegate) (*MsgInterfluidUndelegateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterfluidUndelegate not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_InterfluidDelegate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInterfluidDelegate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InterfluidDelegate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.v12.interfluidsender.Msg/InterfluidDelegate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InterfluidDelegate(ctx, req.(*MsgInterfluidDelegate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InterfluidUndelegate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInterfluidUndelegate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InterfluidUndelegate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.v12.interfluidsender.Msg/InterfluidUndelegate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InterfluidUndelegate(ctx, req.(*MsgInterfluidUndelegate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.v12.interfluidsender.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InterfluidDelegate",
			Handler:    _Msg_InterfluidDelegate_Handler,
		},
		{
			MethodName: "InterfluidUndelegate",
			Handler:    _Msg_InterfluidUndelegate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/interfluidsender/tx.proto",
}

func (m *MsgInterfluidDelegate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInterfluidDelegate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInterfluidDelegate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddr) > 0 {
		i -= len(m.ValAddr)
		copy(dAtA[i:], m.ValAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LockId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LockId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInterfluidDelegateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInterfluidDelegateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInterfluidDelegateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgInterfluidUndelegate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInterfluidUndelegate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInterfluidUndelegate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LockId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LockId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInterfluidUndelegateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInterfluidUndelegateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInterfluidUndelegateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInterfluidDelegate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LockId != 0 {
		n += 1 + sovTx(uint64(m.LockId))
	}
	l = len(m.ValAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInterfluidDelegateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgInterfluidUndelegate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LockId != 0 {
		n += 1 + sovTx(uint64(m.LockId))
	}
	return n
}

func (m *MsgInterfluidUndelegateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInterfluidDelegate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInterfluidDelegate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInterfluidDelegate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockId", wireType)
			}
			m.LockId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInterfluidDelegateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInterfluidDelegateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInterfluidDelegateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInterfluidUndelegate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInterfluidUndelegate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInterfluidUndelegate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockId", wireType)
			}
			m.LockId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInterfluidUndelegateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInterfluidUndelegateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInterfluidUndelegateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
